### ISSUE TITLE
Command `$eval` not managed by FongoDB

### ISSUE THREAD

**Issue by pvardanega** [fakemongo/fongo#102]
When using fongo and trying to [evaluate some instructions](http://docs.mongodb.org/manual/reference/method/db.eval/) as string, an exception is thrown:
```
org.apache.maven.plugin.MojoExecutionException: Error while executing instructions from file 'junit1462803847395374182.tmp': no such cmd: $eval
	at com.github.joelittlejohn.embedmongo.InitDataMongoMojo.execute(InitDataMongoMojo.java:92)
	at com.github.joelittlejohn.embedmongo.InitDataMongoMojoTest.should_execute_instructions(InitDataMongoMojoTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:168)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.[...]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: com.mongodb.CommandFailureException: { "serverUsed" : "localhost:27017" , "ok" : 0 , "errmsg" : "no such cmd: $eval"}
	at com.mongodb.CommandResult.getException(CommandResult.java:76)
	... 31 more
```

**Comment by pvardanega** [comment]
Do you know when the next version will be released? I need this fix to improve one pull request of [embedmongo-maven-plugin](https://github.com/joelittlejohn/embedmongo-maven-plugin/pull/40)

**Comment by twillouer** [comment]
@pvardanega I will to it in few minutes if you need.

But.. did you mean that embededmongo can run with Fongo ?

**Comment by pvardanega** [comment]
It was just for testing purpose but it is not necessary anymore because I took example on Fongo to create a fake instance of com.mongodb.DB.
So no need to release a Fongo version just for me.

**Comment by twillouer** [comment]
@pvardanega too late

**Comment by pvardanega** [comment]
OK, thank you :+1:

**Comment by evantd** [comment]
This doesn't actually appear to be fixed. It no longer throws an exception, but it also doesn't run the script. The implementation appears to just return success without doing anything.

Use case: I use a script to specify the initial state of the DB, so I drop collections and run the script before each test.

I'm trying to migrate existing tests to Fongo, and unfortunately this makes it look like I won't be able to.

**Comment by twillouer** [comment]
$eval is very difficult to implement, the only meaning of the PR is to silently ignore $eval.

For my own test, I directly use the api (or I parse Json with JSONParser)

**Comment by evantd** [comment]
Yes, I can see how it would be! Parsing the json has the added issue of bson being a bit non-standard, what with the type specifications, plus I was actually doing some looping. It was a bit tedious, but I migrated my 500+ line init script to Java without too much trouble. I'm excited to have better testing on our build box without external dependencies. Thanks!
