### ISSUE TITLE
DuplicateKeyException on sparse unique CompoundIndex in subcollection being empty list

### ISSUE THREAD

**Issue by tkruse** [fakemongo/fongo#105]
Hi,

To reproduce

```
@CompoundIndexes({
        @CompoundIndex(name = "foo_idx",
                unique = true,
                sparse = true,
                def = "{'bars._id' : 1}")
})
@Document
public class Foo implements Serializable {
    @Field("bars")
    private List<Bar> applications = new ArrayList<>(); // null is ok
}

@Document
public class Bar implements Serializable {
    @Field("_id")
    private String id;
}

@Test
    public void testSave() throws Exception {

        vacancyRepository.save(new Foo());
        vacancyRepository.save(new Foo());
    }
```

yields something like:

```
repositories.FooTest > testSave FAILED
    org.springframework.dao.DuplicateKeyException: { "serverUsed" : "localhost:27017" , "ok" : 1.0 , "err" : "E11000 duplicate key error index: foo_idx  dup key : {[[5501b92f44aeab6043550e9b]] }" , "code" : 11001}; nested exception is com.mongodb.MongoException$DuplicateKey: { "serverUsed" : "localhost:27017" , "ok" : 1.0 , "err" : "E11000 duplicate key error index: foo_idx  dup key : {[[5501b92f44aeab6043550e9b]] }" , "code" : 11001}
        at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:55)
        at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:1934)
        at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:412)
        at org.springframework.data.mongodb.core.MongoTemplate.saveDBObject(MongoTemplate.java:945)
```

I believe MongoDB does not raise this.

Produced using Java7 with Fongo 1.5.10 and 1.6.1

**Comment by twillouer** [comment]
Ok, I think the problem is on sparse index, who are not handled in Fongo
