### ISSUE TITLE
$and/$or/$nor must be a nonempty array

### ISSUE THREAD

**Issue by keinesorgen** [fakemongo/fongo#110]
Fongo returns value 0 when I run this code 

	void test(MongoDbFactory mongo) {	
        DBObject[] sub = new DBObject[0];
        DBObject query = QueryBuilder.start().or(sub).get();						
		mongo.getDb("d").getCollection("c").count(query);
	}
	
but Mongo throws exception

```
com.mongodb.CommandFailureException: { "serverUsed" : "127.0.0.1:27017" , "ok" : 0.0 , "errmsg" : "$and/$or/$nor must be a nonempty array" , "code" : 2}
	at com.mongodb.CommandResult.getException(CommandResult.java:76)
	at com.mongodb.CommandResult.throwOnError(CommandResult.java:131)
	at com.mongodb.DBCollection.getCount(DBCollection.java:1198)
	at com.mongodb.DBCollection.getCount(DBCollection.java:1153)
	at com.mongodb.DBCollection.getCount(DBCollection.java:1137)
	at com.mongodb.DBCollection.getCount(DBCollection.java:1106)
	at com.mongodb.DBCollection.count(DBCollection.java:1039)
```

**Comment by twillouer** [comment]
Hi,

witch version of MongoDB do you use ?

```java
  /**
   * see https://github.com/fakemongo/fongo/issues/110
   */
  @Test
  public void should_$and_on_an_array_throw_exception() {
    // Given
    DBCollection collection = newCollection();

    DBObject[] sub = new DBObject[0];
    DBObject query = QueryBuilder.start().or(sub).get();
//    ExpectedMongoException.expectCommandFailure(exception, 2);
//    exception.expectMessage("$and/$or/$nor must be a nonempty array");

    // When
    final long count = collection.count(query);

    // Then
    assertThat(count).isEqualTo(0);
  }
```

work fine (mongo 2.6.3)

**Comment by KeineSorgen** [comment]
I use db version v3.0.2

```
2015-04-28T10:56:49.182+0200 I CONTROL  [initandlisten] targetMinOS: Windows 7/Windows Server 2008 R2
2015-04-28T10:56:49.185+0200 I CONTROL  [initandlisten] db version v3.0.2
2015-04-28T10:56:49.190+0200 I CONTROL  [initandlisten] git version: 6201872043ecbbc0a4cc169b5482dcf385fc464f
2015-04-28T10:56:49.194+0200 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1m-fips 19 Mar 2015
2015-04-28T10:56:49.199+0200 I CONTROL  [initandlisten] build info: windows sys.getwindowsversion(major=6, minor=1, build=7601, platform=2, service_pack='Servic
e Pack 1') BOOST_LIB_VERSION=1_49
```

**Comment by Hasnaa-Ibraheem** [comment]
As per [mongo documentation](https://docs.mongodb.com/manual/reference/operator/query/or/)

> The $or operator performs a logical OR operation on an array of **two or more expressions** and selects the documents that satisfy at least one of the expressions. 

In my case, it properly resolves lists to array as using this mongo driver version: 3.4.2
hth
