### ISSUE TITLE
Deadlock situation on concurrently removing and adding Collections under 1.6.2

### ISSUE THREAD

**Issue by sourcekick** [fakemongo/fongo#111]
I observed a pretty reproducible thread deadlock with fongo 1.6.2 and I give some details in the following. Note that I cannot provide the code from the project, but the problem occured in several different places during some JUnit Integration Test setUp and tearDown phases.

Note that the Thread 1 is dropping a Document Collection while Thread 2 is somehow initializing a Document Collection.

Masked output from VisualVM 1.3.8:

```
Found one Java-level deadlock:
=============================
Thread 1:
  waiting to lock monitor 0x00007fa5cb111228 (object 0x0000000742cf8978, a java.util.Collections$SynchronizedMap),
  which is held by Thread 2
Thread 2:
  waiting to lock monitor 0x00007fa5cd6a93a8 (object 0x0000000742cf86e8, a com.mongodb.FongoDB),
  which is held by Thread 1

Java stack information for the threads listed above:
===================================================
```
Thread 1 was here:
```
	at java.util.Collections$SynchronizedMap.remove(Collections.java:2591)
	- waiting to lock <0x0000000742cf8978> (a java.util.Collections$SynchronizedMap)
	at com.mongodb.FongoDB.removeCollection(FongoDB.java:378)
	- locked <0x0000000742cf86e8> (a com.mongodb.FongoDB)
	at com.mongodb.FongoDBCollection.drop(FongoDBCollection.java:1113)
	at com.github.fakemongo.impl.Aggregator.computeResult(Aggregator.java:65)
	at com.mongodb.FongoDB.doAggregateCollection(FongoDB.java:75)
	at com.mongodb.FongoDB.command(FongoDB.java:205)
	at com.mongodb.DB.command(DB.java:371)
	at com.mongodb.DB.command(DB.java:243)
	at org.springframework.data.mongodb.core.MongoTemplate$1.doInDB(MongoTemplate.java:326)
	at org.springframework.data.mongodb.core.MongoTemplate$1.doInDB(MongoTemplate.java:324)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:394)
	at org.springframework.data.mongodb.core.MongoTemplate.executeCommand(MongoTemplate.java:324)
	at org.springframework.data.mongodb.core.MongoTemplate.aggregate(MongoTemplate.java:1423)
	at org.springframework.data.mongodb.core.MongoTemplate.aggregate(MongoTemplate.java:1346)
	at org.springframework.data.mongodb.core.MongoTemplate.aggregate(MongoTemplate.java:1335)
```

Thread 2 was here:

```
at com.mongodb.FongoDB.addCollection(FongoDB.java)
	- waiting to lock <0x0000000742cf86e8> (a com.mongodb.FongoDB)
	at com.mongodb.FongoDBCollection.addToIndexes(FongoDBCollection.java:1200)
	- locked <0x0000000742cf8a38> (a com.mongodb.FongoDBCollection)
	at com.mongodb.FongoDBCollection.putSizeCheck(FongoDBCollection.java:154)
	at com.mongodb.FongoDBCollection.insert(FongoDBCollection.java:121)
	- locked <0x0000000742cf8a38> (a com.mongodb.FongoDBCollection)
	at com.mongodb.FongoDBCollection.insert(FongoDBCollection.java:93)
	- locked <0x0000000742cf8a38> (a com.mongodb.FongoDBCollection)
	at com.mongodb.DBCollection.insert(DBCollection.java:78)
	at com.mongodb.DBCollection.insert(DBCollection.java:120)
	at com.mongodb.FongoDBCollection.createIndex(FongoDBCollection.java:433)
	- locked <0x00000007b2be8710> (a com.mongodb.FongoDBCollection)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:563)
	at com.mongodb.FongoDBCollection.<init>(FongoDBCollection.java:72)
	at com.mongodb.FongoDB.doGetCollection(FongoDB.java:58)
	- locked <0x0000000742cf8978> (a java.util.Collections$SynchronizedMap)
	at com.mongodb.FongoDB.doGetCollection(FongoDB.java:23)
	at com.mongodb.DB.getCollection(DB.java:164)
	at com.mongodb.DB.createCollection(DB.java:204)
	at com.github.fakemongo.impl.aggregation.PipelineKeyword.createAndInsert(PipelineKeyword.java:47)
	at com.github.fakemongo.impl.aggregation.PipelineKeyword.dropAndInsert(PipelineKeyword.java:43)
	at com.github.fakemongo.impl.aggregation.Group.apply(Group.java:165)
	at com.github.fakemongo.impl.Aggregator.computeResult(Aggregator.java:50)
	at com.mongodb.FongoDB.doAggregateCollection(FongoDB.java:75)
	at com.mongodb.FongoDB.command(FongoDB.java:205)
	at com.mongodb.DB.command(DB.java:371)
	at com.mongodb.DB.command(DB.java:243)
	at org.springframework.data.mongodb.core.MongoTemplate$1.doInDB(MongoTemplate.java:326)
	at org.springframework.data.mongodb.core.MongoTemplate$1.doInDB(MongoTemplate.java:324)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:394)
	at org.springframework.data.mongodb.core.MongoTemplate.executeCommand(MongoTemplate.java:324)
	at org.springframework.data.mongodb.core.MongoTemplate.aggregate(MongoTemplate.java:1423)
	at org.springframework.data.mongodb.core.MongoTemplate.aggregate(MongoTemplate.java:1346)
	at org.springframework.data.mongodb.core.MongoTemplate.aggregate(MongoTemplate.java:1335)
```

One might still figure that the scenario, i.e. what the threads are doing concurrently, is invalid and should never be triggered. However I wanted to post this issue anyhow for the framework developers to judge.

Note that our code works fine under Fongo 1.5.10.

**Comment by twillouer** [comment]
Thanks !

**Comment by kevinconaway** [comment]
@twillouer I'm seeing this as well.  Any update on when 1.6.3 will be released?

**Comment by twillouer** [comment]
done !
will be available in maven in few hours
