### ISSUE TITLE
Deadlock in fongo 1.6.2 with mongo-java-driver 2.13.2

### ISSUE THREAD

**Issue by marekzebrowski** [fakemongo/fongo#120]
I'm using Fongo to in tests, but it deadlocks badly

"pool-8-thread-9-ScalaTest-running-DigestBuilderTests":
	at java.util.Collections$SynchronizedMap.put(Collections.java:2588)
	- waiting to lock <0x0000000795731580> (a java.util.Collections$SynchronizedMap)
	at com.mongodb.FongoDB.addCollection(FongoDB.java:384)
	- locked <0x0000000795731500> (a com.mongodb.FongoDB)
	at com.mongodb.FongoDBCollection.addToIndexes(FongoDBCollection.java:1200)
	- locked <0x0000000795f66210> (a com.mongodb.FongoDBCollection)
	at com.mongodb.FongoDBCollection.update(FongoDBCollection.java:255)
	- locked <0x0000000795f66210> (a com.mongodb.FongoDBCollection)
	at com.mongodb.DBCollection.update(DBCollection.java:214)
	at com.mongodb.DBCollection.save(DBCollection.java:1058)
	
	
"pool-12-thread-4":
	at com.mongodb.FongoDB.addCollection(FongoDB.java:384)
	- waiting to lock <0x0000000795731500> (a com.mongodb.FongoDB)
	at com.mongodb.FongoDBCollection.addToIndexes(FongoDBCollection.java:1200)
	- locked <0x0000000795732c40> (a com.mongodb.FongoDBCollection)
	at com.mongodb.FongoDBCollection.putSizeCheck(FongoDBCollection.java:154)
	at com.mongodb.FongoDBCollection.insert(FongoDBCollection.java:121)
	- locked <0x0000000795732c40> (a com.mongodb.FongoDBCollection)
	at com.mongodb.FongoDBCollection.insert(FongoDBCollection.java:93)
	- locked <0x0000000795732c40> (a com.mongodb.FongoDBCollection)
	at com.mongodb.DBCollection.insert(DBCollection.java:78)
	at com.mongodb.DBCollection.insert(DBCollection.java:120)
	at com.mongodb.FongoDBCollection.createIndex(FongoDBCollection.java:433)
	- locked <0x0000000795f95ca0> (a com.mongodb.FongoDBCollection)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:597)
	at com.mongodb.FongoDBCollection.<init>(FongoDBCollection.java:72)
	at com.mongodb.FongoDB.doGetCollection(FongoDB.java:58)
	- locked <0x0000000795731580> (a java.util.Collections$SynchronizedMap)
	at com.mongodb.FongoDB.doGetCollection(FongoDB.java:23)
	at com.mongodb.DB.getCollection(DB.java:175)

**Comment by twillouer** [comment]
Thanks for the report.

I will try to remove the deadlock, but, I think a better solution would be creating a single Fongo object for each Thread

**Comment by marekzebrowski** [comment]
Well, that is not possible or at least very hard in case of my tests, as they run in parallel. Probably they aren't really "unit"

**Comment by twillouer** [comment]
Hi again, can you test agains the master branch, in 1.6.3-SNAPSHOT please ?

**Comment by marekzebrowski** [comment]
I'll run test and get back with results

**Comment by marekzebrowski** [comment]
I ran tests several times in and they passed - so it seems good to me. Thanks!

**Comment by twillouer** [comment]
cool
