### ISSUE TITLE
java.lang.NullPointerException is thrown when Junit test is finished

### ISSUE THREAD

**Issue by Valijon** [fakemongo/fongo#122]
<dependency>
		<groupId>com.github.fakemongo</groupId>
		<artifactId>fongo</artifactId>
		<version>2.0.1</version>
		<scope>test</scope>
	</dependency>
	
	<dependency>
		<groupId>org.mongodb</groupId>
		<artifactId>mongo-java-driver</artifactId>
		<version>3.0.2</version>
	</dependency>

	21:58:27,748 DEBUG DisposableBeanAdapter:227 - Invoking destroy() on bean with name 'mongoDbFactory'
	21:58:27,748 DEBUG DisposableBeanAdapter:303 - Invoking destroy method 'close' on bean with name 'mongo'
	21:58:27,751  WARN DisposableBeanAdapter:335 - Invocation of destroy method 'close' failed on bean with name 'mongo'	
	java.lang.NullPointerException
		at com.mongodb.Mongo.close(Mongo.java:471)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:601)
		at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:328)
		at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:254)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:510)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:486)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:751)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:455)
		at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1092)
		at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1066)
		at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:982)

**Comment by twillouer** [comment]
Right, thanks for the report.

You can try against the v3 branch

**Comment by Valijon** [comment]
Thank you

**Comment by Valijon** [comment]
Works perfectly!!!
