### ISSUE TITLE
And/or Operation with empty array

### ISSUE THREAD

**Issue by yvladimirov** [fakemongo/fongo#123]
Hello. I'm used fongo 2.0 and spring-mongo 1.7

if I used this code and Fongo - No problem
mongoOperations.find(Query.query(Criteria.where("test").andOperator(new Criteria[0])), Test.class)

But if I used Mongo
```java
Caused by: com.mongodb.MongoQueryException: Query failed with error code 14816 and error message '$and expression must be a nonempty array' on server 
	at com.mongodb.connection.ProtocolHelper.getQueryFailureException(ProtocolHelper.java:91)
	at com.mongodb.connection.QueryProtocol.receiveMessage(QueryProtocol.java:288)
	at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:229)
	at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:38)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:155)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:219)
	at com.mongodb.connection.DefaultServerConnection.query(DefaultServerConnection.java:166)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:397)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:394)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:195)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:168)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:394)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:57)
	at com.mongodb.Mongo.execute(Mongo.java:736)
	at com.mongodb.Mongo$2.execute(Mongo.java:723)
	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:815)
	at com.mongodb.DBCursor.hasNext(DBCursor.java:149)
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:1871)
	... 38 more
```

But in mongo is not bug
https://jira.mongodb.org/browse/DOCS-2139

**Comment by twillouer** [comment]
Thanks, there is already the #110

**Comment by yvladimirov** [comment]
Ooo Sorry!

**Comment by twillouer** [comment]
don't worry, my fault.

can you test against the v3 branche ?

**Comment by yvladimirov** [comment]
Yes. It's work! Thanks

```java
Caused by: com.mongodb.MongoCommandException: Command failed with error 2: 'null' on server localhost:27017. The full response is { "ok" : 0.0, "err" : "$and/$or/$nor must be a nonempty array", "code" : 2 }
	at com.mongodb.CommandResult.getException(CommandResult.java:80)
	at com.mongodb.CommandResult.throwOnError(CommandResult.java:94)
	at com.mongodb.FongoDBCollection.buildFilter(FongoDBCollection.java:1495)
	at com.mongodb.FongoDBCollection.__find(FongoDBCollection.java:560)
	at com.mongodb.FongoDBCursor.fetch(FongoDBCursor.java:60)
	at com.mongodb.FongoDBCursor.hasNext(FongoDBCursor.java:90)
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:1871)
	... 38 more
```
