### ISSUE TITLE
Bug: listing indexes 

### ISSUE THREAD

**Issue by FeNoMeNa** [fakemongo/fongo#131]
When I invoke ```ListIndexesIterable<Document> listIndexes();``` of ```MongoCollection```, and then try to get an composite item (Document object) from the iterable structure, I'm getting the following exception:

```java
java.lang.ClassCastException: com.mongodb.BasicDBObject cannot be cast to org.bson.Document
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by twillouer** [comment]
Hi, can you retry againts the v3 branch ?

`mvn clean install`

**Comment by rzanner** [comment]
...the same issue here - I need to work around this by using the old API of the driver!

**Comment by twillouer** [comment]
@rzanner witch version of fongo ? 2.0.3 ?

**Comment by rzanner** [comment]
2.0.2

**Comment by twillouer** [comment]
Witch method do you call on the `ListIndexesIterable` object ?
`into` seems to work fine

**Comment by rzanner** [comment]
I was just iterating the ListIndexesIterable<Document>, like this:
```
        ListIndexesIterable<Document> indexes = from.listIndexes();
        for (Document index : indexes) {
            Bson keys = (Bson) index.get("key");
            String name = (String) index.get("name");
            Object unique = index.get("unique");
            LOGGER.debug("Found index {}!", name);
            // ...
        }
```

**Comment by twillouer** [comment]
Hi,

can you test against the v3 branch (need mongo 3.2 drivers)

**Comment by rzanner** [comment]
I'll check tomorrow...
