### ISSUE TITLE
Deadlock in Fongo 1.6.3

### ISSUE THREAD

**Issue by kevinconaway** [fakemongo/fongo#132]
@twillouer similar to #120 and #111, I'm seeing a different deadlock issue in 1.6.3

Below is the output from the thread dump

```
build	12-Aug-2015 13:53:37	JNI global references: 396
build	12-Aug-2015 13:53:37	Found one Java-level deadlock:
build	12-Aug-2015 13:53:37	=============================
build	12-Aug-2015 13:53:37	"qtp1956382313-28":
build	12-Aug-2015 13:53:37	  waiting to lock monitor 0x00007f75fc006bf8 (object 0x0000000731ecc9e0, a com.mongodb.FongoDB),
build	12-Aug-2015 13:53:37	  which is held by "main"
build	12-Aug-2015 13:53:37	"main":
build	12-Aug-2015 13:53:37	  waiting to lock monitor 0x00007f7674003b98 (object 0x00000007375b8d10, a com.mongodb.FongoDBCollection),
build	12-Aug-2015 13:53:37	  which is held by "qtp1956382313-28"
build	12-Aug-2015 13:53:37	Java stack information for the threads listed above:
build	12-Aug-2015 13:53:37	===================================================
build	12-Aug-2015 13:53:37	"qtp1956382313-28":
build	12-Aug-2015 13:53:37		at com.mongodb.FongoDB.addCollection(FongoDB.java)
build	12-Aug-2015 13:53:37		- waiting to lock <0x0000000731ecc9e0> (a com.mongodb.FongoDB)
build	12-Aug-2015 13:53:37		at com.mongodb.FongoDBCollection.addToIndexes(FongoDBCollection.java:1199)
build	12-Aug-2015 13:53:37		- locked <0x00000007375b8d10> (a com.mongodb.FongoDBCollection)
build	12-Aug-2015 13:53:37		at com.mongodb.FongoDBCollection.putSizeCheck(FongoDBCollection.java:154)
build	12-Aug-2015 13:53:37		at com.mongodb.FongoDBCollection.insert(FongoDBCollection.java:121)
build	12-Aug-2015 13:53:37		- locked <0x00000007375b8d10> (a com.mongodb.FongoDBCollection)
build	12-Aug-2015 13:53:37		at com.mongodb.DBCollection.insert(DBCollection.java:161)
build	12-Aug-2015 13:53:37		at com.mongodb.DBCollection.insert(DBCollection.java:107)
build	12-Aug-2015 13:53:37		at com.mongodb.DBCollection.save(DBCollection.java:1049)
build	12-Aug-2015 13:53:37		at com.mongodb.DBCollection.save(DBCollection.java:1014)
build	12-Aug-2015 13:53:37		at org.springframework.data.mongodb.core.MongoTemplate$11.doInCollection(MongoTemplate.java:1030)
build	12-Aug-2015 13:53:37		at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:458)
build	12-Aug-2015 13:53:37		at org.springframework.data.mongodb.core.MongoTemplate.saveDBObject(MongoTemplate.java:1025)
build	12-Aug-2015 13:53:37		at org.springframework.data.mongodb.core.MongoTemplate.doSave(MongoTemplate.java:965)
build	12-Aug-2015 13:53:37		at org.springframework.data.mongodb.core.MongoTemplate.save(MongoTemplate.java:911)
...snip...

build	12-Aug-2015 13:53:37	"main":
build	12-Aug-2015 13:53:37		at com.mongodb.FongoDBCollection._dropIndexes(FongoDBCollection.java)
build	12-Aug-2015 13:53:37		- waiting to lock <0x00000007375b8d10> (a com.mongodb.FongoDBCollection)
build	12-Aug-2015 13:53:37		at com.mongodb.FongoDBCollection.drop(FongoDBCollection.java:1112)
build	12-Aug-2015 13:53:37		at com.mongodb.FongoDB.dropDatabase(FongoDB.java:133)
build	12-Aug-2015 13:53:37		- locked <0x0000000731ecc9e0> (a com.mongodb.FongoDB)
build	12-Aug-2015 13:53:37		at com.github.fakemongo.Fongo.dropDatabase(Fongo.java:95)
build	12-Aug-2015 13:53:37		at com.mongodb.MockMongoClient.dropDatabase(MockMongoClient.java:58)
...snip...
```

Does FongoDB#dropDatabase() need to be synchronized?  It seems like that might fix the issue.

**Comment by kevinconaway** [comment]
Here is a test harness that exposes the issue, at least on my machine

```java
import com.github.fakemongo.Fongo;
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;

import java.util.concurrent.CyclicBarrier;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

public class Issue132 {

    public static void main(String [] args) throws Exception {
        Fongo fongo = new Fongo("deadlock");

        MongoClient client = fongo.getMongo();
        String databaseName = "test";

        CyclicBarrier barrier = new CyclicBarrier(2);
        ExecutorService service = Executors.newCachedThreadPool();

        service.submit(() -> {
            try {
                barrier.await();

                for (int i=0; i < 1000000; i++) {
                    DBCollection collection = client.getDB(databaseName).getCollection("test");

                    DBObject object = new BasicDBObject();
                    object.put("name", String.valueOf(System.currentTimeMillis()));

                    collection.insert(object);
                }

            } catch (Throwable ex) {
                System.err.println("Error while inserting to db");
                ex.printStackTrace();
            }
        });

        service.submit(() -> {
            try {
                barrier.await();

                for (int i=0; i < 1000000; i++) {
                    client.dropDatabase(databaseName);
                }

            } catch (Throwable ex) {
                System.err.println("Error while dropping db");
                ex.printStackTrace();
            }
        });

        service.shutdown();
        service.awaitTermination(1, TimeUnit.DAYS);
    }

}
```

**Comment by kevinconaway** [comment]
I tested the above class with the fix provided in https://github.com/fakemongo/fongo/pull/133 and the test passes.

**Comment by twillouer** [comment]
Thanks, I try to fix it but... it's too difficult for me :)

For my information, why do you use the same Fongo object for dropping a collection when you insert data ?

**Comment by kevinconaway** [comment]
Its used in a spring boot integration test.  The fongo database is a shared resource and the database is dropped between each test

However, the server side of the test appears to be running while the test is cleaning up.  Theres probably a better way to implement this on my end.

**Comment by twillouer** [comment]
Thanks, I try to fix it but... it's too difficult for me :)

For my information, why do you use the same Fongo object for dropping a collection when you insert data ?

**Comment by kevinconaway** [comment]
@twilouer do you need anything else from me on this one?

**Comment by Jimilian** [comment]
This commit fixed this deadlock: https://github.com/Jimilian/fongo/commit/bf81309b93381d935afd13e7070194eac116e8bb

**Comment by twillouer** [comment]
Thanks. Can you do a PR ?

**Comment by Jimilian** [comment]
Yes, https://github.com/fakemongo/fongo/pull/155

**Comment by TreyParrish** [comment]
doesn't look like this fix ever made it into 2.x? Specifically #133
