### ISSUE TITLE
Bulk execution with failure throws DuplicateKey instead of BulkWriteException

### ISSUE THREAD

**Issue by Tolsi** [fakemongo/fongo#135]
Try execute test with many bulks upsert update ops, they try to insert some objects subject to unique conditions (error case). With fongo I have this exception:
```
com.mongodb.MongoException$DuplicateKey: { "serverUsed" : "localhost:27017" , "ok" : 1.0 , "code" : 11000 , "err" : "E11000 duplicate key error index: test.collection.date_val_idx  dup key : {[[2015-08-21], [8]] }"}
	at com.mongodb.CommandResult.getWriteException(CommandResult.java:88)
	at com.mongodb.CommandResult.getException(CommandResult.java:79)
	at com.mongodb.CommandResult.throwOnError(CommandResult.java:140)
	at com.mongodb.FongoDBCollection.addToIndexes(FongoDBCollection.java:1180)
	at com.mongodb.FongoDBCollection.putSizeCheck(FongoDBCollection.java:154)
	at com.mongodb.FongoDBCollection.fInsert(FongoDBCollection.java:201)
	at com.mongodb.FongoDBCollection.update(FongoDBCollection.java:276)
	at com.mongodb.FongoDBCollection.executeBulkWriteOperation(FongoDBCollection.java:1026)
	at com.mongodb.DBCollection.executeBulkWriteOperation(DBCollection.java:1737)
	at com.mongodb.BulkWriteOperation.execute(BulkWriteOperation.java:109)
	at com.mongodb.casbah.BulkWriteOperation$$anonfun$2.apply(BulkWriteOperation.scala:88)
	at com.mongodb.casbah.BulkWriteOperation$$anonfun$2.apply(BulkWriteOperation.scala:88)
	at scala.util.Try$.apply(Try.scala:191)
	at com.mongodb.casbah.BulkWriteOperation.execute(BulkWriteOperation.scala:88)
...
```
but real mongo db v 3.0.2 throws:
```
com.mongodb.casbah.BulkWriteException: Bulk write operation error on server test:27017. Write errors: [BulkWriteError{index=0, code=11000, message='E11000 duplicate key error collection: test.segments index: date_val_idx dup key: { : "2015-08-21", : "8" }', details={ }}, BulkWriteError{index=1, code=11000, message='E11000 duplicate key error collection: test.segments index: date_val_idx dup key: { : "2015-08-21", : "4" }', details={ }}, BulkWriteError{index=2, code=11000, message='E11000 duplicate key error collection: test.segments index: date_val_idx dup key: { : "2015-08-21", : "9" }', details={ }}, BulkWriteError{index=3, code=11000, message='E11000 duplicate key error collection: test.segments index: date_val_idx dup key: { : "2015-08-21", : "5" }', details={ }}, BulkWriteError{index=4, code=11000, message='E11000 duplicate key error collection: test.segments index: date_val_idx dup key: { : "2015-08-21", : "10" }', details={ }}, BulkWriteError{index=5, code=11000, message='E11000 duplicate key error collection: test.segments index: date_val_idx dup key: { : "2015-08-21", : "6" }', details={ }}, BulkWriteError{index=6, code=11000, message='E11000 duplicate key error collection: test.segments index: date_val_idx dup key: { : "2015-08-21", : "1" }', details={ }}, BulkWriteError{index=7, code=11000, message='E11000 duplicate key error collection: test.segments index: date_val_idx dup key: { : "2015-08-21", : "2" }', details={ }}, BulkWriteError{index=8, code=11000, message='E11000 duplicate key error collection: test.segments index: date_val_idx dup key: { : "2015-08-21", : "7" }', details={ }}, BulkWriteError{index=9, code=11000, message='E11000 duplicate key error collection: test.segments index: date_val_idx dup key: { : "2015-08-21", : "3" }', details={ }}]. 
	at com.mongodb.casbah.BulkWriteOperation.execute(BulkWriteOperation.scala:90)
```

I use casbah 2.8.1 and mongo-java-driver 2.13.1

**Comment by twillouer** [comment]
Hi,

thanks for the report.

**Comment by twillouer** [comment]
Hi,

can you check against the v3 branch ?
