### ISSUE TITLE
NullPointerException when doing a update.pull

### ISSUE THREAD

**Issue by rlemaire** [fakemongo/fongo#147]
Hi,

Given a model like this : 

```java
class A {
    String id;
    Set<B> bs;
}

class B {
    String reference;
    Set<String> ids;
}
```

I have a NullPointerException with fongo 1.6.3, for this request :

```java
mongoOperations.updateFirst(query(where("_id").is(requestedId).and("bs").elemMatch(where("reference").is(reference))), new Update().pull("bs.$.ids", idToPull), A.class);
```

(I use spring-data-mongodb 1.8.0.RELEASE)

The code works fine at runtime with a real mongo and works in a flapdoodle test.

Here's the stack trace : 

```
java.lang.NullPointerException
	at com.github.fakemongo.impl.UpdateEngine$13.mergeAction(UpdateEngine.java:459)
	at com.github.fakemongo.impl.UpdateEngine$BasicUpdate.doSingleKeyUpdate(UpdateEngine.java:94)
	at com.github.fakemongo.impl.UpdateEngine$BasicUpdate.handlePositionalUpdate(UpdateEngine.java:132)
	at com.github.fakemongo.impl.UpdateEngine$BasicUpdate.doSingleKeyUpdate(UpdateEngine.java:79)
	at com.github.fakemongo.impl.UpdateEngine$BasicUpdate.doUpdate(UpdateEngine.java:56)
	at com.github.fakemongo.impl.UpdateEngine.doUpdate(UpdateEngine.java:570)
	at com.mongodb.FongoDBCollection.update(FongoDBCollection.java:262)
	at com.mongodb.DBCollection.update(DBCollection.java:214)
	at com.mongodb.DBCollection.update(DBCollection.java:247)
	at org.springframework.data.mongodb.core.MongoTemplate$12.doInCollection(MongoTemplate.java:1107)
	at org.springframework.data.mongodb.core.MongoTemplate$12.doInCollection(MongoTemplate.java:1087)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:462)
	at org.springframework.data.mongodb.core.MongoTemplate.doUpdate(MongoTemplate.java:1087)
	at org.springframework.data.mongodb.core.MongoTemplate.updateFirst(MongoTemplate.java:1061)
	at MyClass.myMethod(MyClass.java:259)

```

Since I'm not using mongo 3, I can't upgrade to Fongo 2.0.2.

Is this a known issue (with a workaround ?) ? Am I doing something wrong ? 

Thank you.

**Comment by twillouer** [comment]
Hi,
thanks for the report.

Will check

**Comment by rlemaire** [comment]
I reproduced it by pasting code in a small maven project.
