### ISSUE TITLE
Not implemented for command : { "dropDatabase" : 1}

### ISSUE THREAD

**Issue by ddossot** [fakemongo/fongo#157]
Using fongo `2.0.3`, this works:

    new Fongo("test").getDB("foo").dropDatabase();

but not that:

    new Fongo("test").getDatabase("foo").drop();

which throws:
<pre>com.github.fakemongo.FongoException: Not implemented for command : { "dropDatabase" : 1}
	at com.github.fakemongo.FongoConnection.command(FongoConnection.java:408)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:166)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:137)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:111)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:103)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:98)
	at com.mongodb.operation.DropDatabaseOperation.execute(DropDatabaseOperation.java:51)
	at com.mongodb.operation.DropDatabaseOperation.execute(DropDatabaseOperation.java:36)
	at com.github.fakemongo.Fongo.execute(Fongo.java:185)
	at com.mongodb.MongoDatabaseImpl.drop(MongoDatabaseImpl.java:122)
	at com.mongodb.FongoMongoDatabase.drop(FongoMongoDatabase.java:11)</pre>

**Comment by twillouer** [comment]
Hi,

yes, it's in the next release (see b559241a2de5ecd3af441a9bac301bcae995f90f)

**Comment by ddossot** [comment]
Great. I'm happy to confirm it works fine with a locally built `2.0.4-SNAPSHOT` :+1:
