### ISSUE TITLE
FongoException: Don't know how to compare class java.lang.String and class java.util.UUID

### ISSUE THREAD

**Issue by mrjbee** [fakemongo/fongo#166]
Driver: 2.X
Version: 1.6.4

Im not sure if it a feature and I did something wrong or its a defect, but while I was truing to replace real mongo in our unit tests, I faced with:

```
com.github.fakemongo.FongoException: Don't know how to compare class java.lang.String and class java.util.UUID values are : some string vs dde3e775-788d-418a-9c5b-f2f57e8b03cf
	at com.github.fakemongo.impl.ExpressionParser.compareTo(ExpressionParser.java:686)
	at com.github.fakemongo.impl.ExpressionParser.compareObjects(ExpressionParser.java:607)
	at com.github.fakemongo.impl.ExpressionParser.compareObjects(ExpressionParser.java:576)
	at com.github.fakemongo.impl.ExpressionParser$15.apply(ExpressionParser.java:559)
	at com.github.fakemongo.impl.ExpressionParser$AndFilter.apply(ExpressionParser.java:938)
	at com.mongodb.FongoDBCollection.__find(FongoDBCollection.java:507)
	at com.mongodb.FongoDBCollection.findOne(FongoDBCollection.java:439)
	at com.mongodb.DBCollection.findOne(DBCollection.java:789)
	at com.avid.central.shortcuts.impl.FongoTest.should not found but throw exception instead(FongoTest.groovy:54)
```

I`ve wrote a simple test to reproduce exception
```java
class FongoTest extends Specification {

    Fongo fakeMongo =  new Fongo("fake mongo");
    MongoClient  fakeMongoClient = fakeMongo.getMongo();
    DBCollection mongoCollection = fakeMongo.getDB("shortcut").getCollection("shortcut");
 
    def 'should not found but throw exception instead'() {
        when:
            final BasicDBObject shortcut = new BasicDBObject();
            UUID id = UUID.randomUUID();
            shortcut.put("id", id);
            mongoCollection.insert(shortcut);
        and:
            final BasicDBObject whereQuery = new BasicDBObject();
            whereQuery.put("id", "some string");
            //Got an exception here
            DBObject actual = mongoCollection.findOne(whereQuery).get("id")
        then:
            actual == null
    }
}
```

**Comment by twillouer** [comment]
Hi, you can test against the "master" branch :)

**Comment by mrjbee** [comment]
@twillouer hi, sorry, we did move to de.flapdoodle.embed.mongo So dont have env to test fongo in nearest future.
P/S was not expect to get so quick support. Awesome :+1:

**Comment by mrjbee** [comment]
Tested with 1.6.5, works like charm
Thanks, sorry for delay
