### ISSUE TITLE
Read concern can not be null exception with MongoDB driver 3.2.0

### ISSUE THREAD

**Issue by ddossot** [fakemongo/fongo#167]
Using mongo-java-driver `3.2.0` with fongo `2.0.3` fails when calling `db.getCollection()`:
<pre>
java.lang.IllegalArgumentException: readConcern can not be null
	at com.mongodb.assertions.Assertions.notNull(Assertions.java:37)
	at com.mongodb.operation.FindOperation.readConcern(FindOperation.java:474)
	at com.mongodb.DBCollection.findOne(DBCollection.java:769)
	at com.mongodb.DBCollection.findOne(DBCollection.java:747)
	at com.mongodb.DBCollection.findOne(DBCollection.java:694)
	at com.mongodb.FongoDBCollection.createIndex(FongoDBCollection.java:462)
	at com.mongodb.FongoDBCollection.<init>(FongoDBCollection.java:80)
	at com.mongodb.FongoDB.doGetCollection(FongoDB.java:80)
	at com.mongodb.FongoDB.getCollection(FongoDB.java:73)
	at org.mongodb.morphia.DatastoreImpl.getCollection(DatastoreImpl.java:793)
	at org.mongodb.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:302)
	at org.mongodb.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:297)
	at org.mongodb.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:496)
	at org.mongodb.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:488)
</pre>

**Comment by twillouer** [comment]
hi, see v3 branch please :)

**Comment by mmoayyed** [comment]
So, based on your response I am assuming this will be accounted for in v3 of fongo? 

Note that spring does not seem to support this yet in their schema.

**Comment by ddossot** [comment]
@mmoayyed This fix is available in Fongo `2.0.4`.

**Comment by mmoayyed** [comment]
Very good. I am just going to have to convince Spring them to switch support for 3.2.x of Mongo! Thank you.

**Comment by balone1988** [comment]
This issue seems to have returned in 2.0.7:

```
[error] Caused by: java.lang.IllegalArgumentException: readConcern can not be null
[error]     at com.mongodb.assertions.Assertions.notNull(Assertions.java:37)
[error]     at com.mongodb.operation.FindOperation.readConcern(FindOperation.java:476)
[error]     at com.mongodb.DBCollection.findOne(DBCollection.java:769)
[error]     at com.mongodb.DBCollection.findOne(DBCollection.java:747)
[error]     at com.mongodb.DBCollection.findOne(DBCollection.java:694)
[error]     at com.mongodb.FongoDBCollection.createIndex(FongoDBCollection.java:462)
[error]     at com.mongodb.FongoDBCollection.<init>(FongoDBCollection.java:80)
[error]     at com.mongodb.FongoDB.doGetCollection(FongoDB.java:80)
[error]     at com.mongodb.FongoDB.getCollection(FongoDB.java:73)
[error]     at com.mongodb.FongoDB.createCollection(FongoDB.java:66)
[error] Caused by: java.lang.IllegalArgumentException: readConcern can not be null
[error]     at com.mongodb.assertions.Assertions.notNull(Assertions.java:37)
[error]     at com.mongodb.operation.FindOperation.readConcern(FindOperation.java:476)
[error]     at com.mongodb.DBCollection.findOne(DBCollection.java:769)
[error]     at com.mongodb.DBCollection.findOne(DBCollection.java:747)
[error]     at com.mongodb.DBCollection.findOne(DBCollection.java:694)
[error]     at com.mongodb.FongoDBCollection.createIndex(FongoDBCollection.java:462)
[error]     at com.mongodb.FongoDBCollection.<init>(FongoDBCollection.java:80)
[error]     at com.mongodb.FongoDB.doGetCollection(FongoDB.java:80)
[error]     at com.mongodb.FongoDB.getCollection(FongoDB.java:73)
[error]     at com.mongodb.FongoDB.createCollection(FongoDB.java:66)
```

I was using mongodb-driver 3.2.2 with fongo 2.0.7.

I have reverted to 2.0.4 for now.

**Comment by twillouer** [comment]
Hi,

it's working on my machine, can you please provide the "real" call ?
