### ISSUE TITLE
Support Mongo Java Driver 3.2.x

### ISSUE THREAD

**Issue by rzanner** [fakemongo/fongo#169]
The constructor of MongoDatabaseImpl has changed - now supports a "readPreference" parameter. Switching to the new driver results in "NoSuchMethodError":

```
java.lang.NoSuchMethodError: com.mongodb.MongoDatabaseImpl.<init>(Ljava/lang/String;Lorg/bson/codecs/configuration/CodecRegistry;Lcom/mongodb/ReadPreference;Lcom/mongodb/WriteConcern;Lcom/mongodb/operation/OperationExecutor;)V
        at com.mongodb.FongoMongoDatabase.<init>(FongoMongoDatabase.java:20)
        at com.mongodb.FongoMongoDatabase.<init>(FongoMongoDatabase.java:16)
        at com.mongodb.MockMongoClient.getDatabase(MockMongoClient.java:63)
        at com.github.fakemongo.Fongo.getDatabase(Fongo.java:95)
        ...
```

**Comment by twillouer** [comment]
Thanks.
Can you check againt the v3 branch before release ?

**Comment by rzanner** [comment]
Hi, the v3 branch using MongoDB Java driver version 3.2.0 looks fine - looking forward to the next release! ;-)
