### ISSUE TITLE
Support Mongo Java Driver 3.1.x (?)

### ISSUE THREAD

**Issue by rzanner** [fakemongo/fongo#170]
The interface "com.mongodb.connection.Connection" has changed - new methods have been added (e.g. "killCursor(MongoNamespace, List<Long>)", also see "since 3.1" tags). 

Switching to the new driver results in "AbstractMethodError":
```
java.lang.AbstractMethodError: com.github.fakemongo.FongoConnection.query(Lcom/mongodb/MongoNamespace;Lorg/bson/BsonDocument;Lorg/bson/BsonDocument;IIIZZZZZZLorg/bson/codecs/Decoder;)Lcom/mongodb/connection/QueryResult;
        at com.mongodb.operation.FindOperation$1.call(FindOperation.java:397)
        at com.mongodb.operation.FindOperation$1.call(FindOperation.java:394)
        at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:196)
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:169)
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:394)
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:57)
        at com.github.fakemongo.Fongo.execute(Fongo.java:156)
        at com.mongodb.FindIterableImpl$FindOperationIterable.first(FindIterableImpl.java:197)
        at com.mongodb.FindIterableImpl.first(FindIterableImpl.java:140)
        ...
```

**Comment by twillouer** [comment]
Hi,

with mongo 3.2 ??

**Comment by twillouer** [comment]
(and the v3 branch ?)

**Comment by rzanner** [comment]
I'll check tomorrow...

**Comment by rzanner** [comment]
Hi, with MongoDB Java driver version 3.1.1 and the locally compiled v3 branch of fongo (2.0.4-SNAPSHOT), I get the following NoSuchMethodError:
```
java.lang.NoSuchMethodError: com.mongodb.MongoClientOptions.getReadConcern()Lcom/mongodb/ReadConcern;
        at com.mongodb.MockMongoClient.create(MockMongoClient.java:32)
        at com.github.fakemongo.Fongo.createMongo(Fongo.java:157)
        at com.github.fakemongo.Fongo.<init>(Fongo.java:73)
        at com.github.fakemongo.Fongo.<init>(Fongo.java:62)
        ...
```

Additionally, the "ReadConcern" class is no longer existent - it's called "ReadPreference" now.

Probably it's best to drop 3.0.x driver support in fongo v3 (since there is a 3.2.x version of the driver now) or create a separate 3.1.x+ branch...

**Comment by twillouer** [comment]
the v3 branch is now only for version 3.2.0 of mongo drivers. It's hard to
maintain for all drivers

**Comment by rzanner** [comment]
Yeah - that's understandable. From my point of view you can close this issue - I won't be using the 3.1.x drivers anyway, when the 3.2.x drivers are supported properly. :-)
