### ISSUE TITLE
listCollectionNames throws ClassCastException

### ISSUE THREAD

**Issue by jawhiting** [fakemongo/fongo#174]
Using Fongo 2.0.4 with the v3 drivers (tried 3.2.0 and 3.1.0 of Mongo), trying to iterate across listCollectionNames gives an exception. 

    Fongo fongo = new Fongo("Test");
    MongoDatabase db = fongo.getDatabase("Test");
    MongoCollection c = db.getCollection("MyCollection");
    c.insertOne(new Document("name", "MongoDB")
            .append("type", "database")
            .append("count", 1)
            .append("info", new Document("x", 203).append("y", 102)));
    MongoIterable<String> names = db.listCollectionNames();
    System.out.println(names.first());

Results in this exception:

    Exception in thread "main" java.lang.ClassCastException: org.bson.Document cannot be cast to org.bson.BsonDocument
    	at com.mongodb.MongoDatabaseImpl$1.apply(MongoDatabaseImpl.java:142)
    	at com.mongodb.MongoMappingCursor.next(MongoMappingCursor.java:44)
    	at com.mongodb.MappingIterable.first(MappingIterable.java:45)
    	at FongoTest.main(FongoTest.java:31)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:497)
    	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

The same code against a real instance of Mongo works fine.

**Comment by twillouer** [comment]
Hi,

see v3 branch

**Comment by jawhiting** [comment]
Looks good thank you!
