### ISSUE TITLE
Unexpected error executing a simple map reduce operation

### ISSUE THREAD

**Issue by jfcorugedo** [fakemongo/fongo#196]
I want to use fongo (1.5.10 and 1.6.6) to test a very simple map reduce operation of my application.

During the execution of the map reduce, fongo trhows an unexpected error:

`java.lang.RuntimeException: json can't serialize type : class org.mozilla.javascript.gen.c1
	at com.mongodb.util.ClassMapBasedObjectSerializer.serialize(ClassMapBasedObjectSerializer.java:77)
	at com.mongodb.util.JSONSerializers$MapSerializer.serialize(JSONSerializers.java:317)
	at com.mongodb.util.ClassMapBasedObjectSerializer.serialize(ClassMapBasedObjectSerializer.java:79)
	at com.mongodb.util.JSONSerializers$IterableSerializer.serialize(JSONSerializers.java:290)
	at com.mongodb.util.ClassMapBasedObjectSerializer.serialize(ClassMapBasedObjectSerializer.java:79)
	at com.mongodb.util.JSONSerializers$MapSerializer.serialize(JSONSerializers.java:317)
	at com.mongodb.util.ClassMapBasedObjectSerializer.serialize(ClassMapBasedObjectSerializer.java:79)
	at com.mongodb.util.JSON.serialize(JSON.java:54)
	at com.mongodb.util.JSON.serialize(JSON.java:40)
	at com.mongodb.BasicDBObject.toString(BasicDBObject.java:97)
	at java.lang.String.valueOf(String.java:2981)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.mongodb.FongoDBCollection.insert(FongoDBCollection.java:114)
	at com.mongodb.DBCollection.insert(DBCollection.java:161)
	...`

The problem is in this line (FongoDBCollection.java:114):

      DBObject cloned = filterLists(Util.cloneIdFirst(encodeDecode(obj, encoder)));
      if (LOG.isDebugEnabled()) {
           LOG.debug("insert: " + cloned);
      }

When Logger tries to obtain a String representation of `cloned` object, it throws a RuntimeException.

If I turn off DEBUG traces of that class (`<logger name="com.mongodb" level="INFO"/>`) then everything works.

Can you take a look?

Thanks!

**Comment by twillouer** [comment]
Hi,

can you try against the master branch ?

I don't know exactly your set of test, can you provide me a simple case ?

**Comment by jfcorugedo** [comment]
Ok, I've tested your change and now it doesn't fail, but it doesn't print the content of the object either.

This line:

    LOG.debug("insert:  {}", cloned);

Outputs this trace:

    2016-03-08 12:37:47,141 [DEBUG] [main] com.mongodb.FongoDBCollection - insert:  [FAILED toString()]
