### ISSUE TITLE
ExpressionParser doesn't handle more than two operators for a single field

### ISSUE THREAD

**Issue by jjmgreen** [fakemongo/fongo#201]
{field:{$exists:true,$ne:[],$nin:["1","2"]}}

fails with

com.github.fakemongo.FongoException: Invalid expression for key [field]: { "$exists" : true , "$ne" : [ ] , "$nin" : [ "1","2"]}
	at com.github.fakemongo.impl.ExpressionParser.buildExpressionFilter(ExpressionParser.java:619)
	at com.github.fakemongo.impl.ExpressionParser.buildExpressionFilter(ExpressionParser.java:561)
	at com.github.fakemongo.impl.ExpressionParser.buildFilter(ExpressionParser.java:330)
	at com.mongodb.FongoDBCollection.buildFilter(FongoDBCollection.java:1566)
	at com.mongodb.FongoDBCollection.__find(FongoDBCollection.java:607)
	at com.mongodb.FongoDBCursor.fetch(FongoDBCursor.java:60)
	at com.mongodb.FongoDBCursor.hasNext(FongoDBCursor.java:90)
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:1904)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1729)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1712)
	at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:602)
	at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:593)

**Comment by twillouer** [comment]
Hi,

can you check against the v3 branch ?
