### ISSUE TITLE
Aggregation using Cursor causing org.bson.Document cannot be cast to com.mongodb.DBObject

### ISSUE THREAD

**Issue by tejkumar51** [fakemongo/fongo#202]
After aggregating using dbcursor in Fakemongo, unable to get DBObjects from cursor (**cursor.next()**)
Throwing the class cast exception 
(Working fine when tested with mongo)

## Exception:
```
Caused by: java.lang.ClassCastException: org.bson.Document cannot be cast to com.mongodb.DBObject
	at com.mongodb.MongoCursorAdapter.next(MongoCursorAdapter.java:51)
	at com.mongodb.MongoCursorAdapter.next(MongoCursorAdapter.java:22)
```

## Example Code snippet: 
_______________
```
com.mongodb.AggregationOptions options = com.mongodb.AggregationOptions.builder()
				.outputMode(com.mongodb.AggregationOptions.OutputMode.CURSOR).batchSize(Integer.valueOf(batchSize))
				.allowDiskUse(true).build();
		DBCollection collection = mongoDbFactory.getDb().getCollection(INVENTORY_BALANCE_ANNUAL);

		List<DBObject> pipeline = new ArrayList<DBObject>(preparePipeline(transactionNumber));
		Cursor cursor = collection.aggregate(pipeline, options);
```
______________
```
try {
			while (cursor.hasNext()) {
				DBObject inventoryBalanceDbObject = cursor.next();
				inventoryBalanceFileWriter.writeEDIRecordToFile(
						buildInventoryBalanceAnnualEDIRecord(inventoryBalanceDbObject), bufferedWriter);
			}
		} catch (Exception e) {
			throw new InventoryBalanceException(EDI_BUILDING_EXCEPTION_MESSAGE, e);
		} finally {
			cursor.close();
		}
```
____________________________

Any idea ?

**Comment by twillouer** [comment]
Yes, will check

**Comment by twillouer** [comment]
Yes, will check

**Comment by twillouer** [comment]
Yes, can you try against the v3 branch ?
