### ISSUE TITLE
Projection on arrays not working

### ISSUE THREAD

**Issue by dnchristiansen** [fakemongo/fongo#223]
I have a document in my collection that looks something like this:

```
{
    "_id" : "MY_ID",
    "arrayData" : [ 
        {
            "obj1" : {
                "prop1" : "foo"
                "prop2" : bar"
            },
            "obj2" : {
                "_id" : "MY_OBJ_ID1",
                "prop3": "asdf",
                "prop4: "asdfasdf"
            }
        }, 
        {
            "obj1" : {
                "prop1" : "foo"
                "prop2" : bar"
            },
            "obj2" : {
                "_id" : "MY_OBJ_ID2",
                "prop3": "asdf",
                "prop4: "asdfasdf"
            }
        }, 
        {
            "obj1" : {
                "prop1" : "foo"
                "prop2" : bar"
            },
            "obj2" : {
                "_id" : "MY_OBJ_ID3",
                "prop3": "asdf",
                "prop4: "asdfasdf"
            }
        }, 
        {
            "obj1" : {
                "prop1" : "foo"
                "prop2" : bar"
            },
            "obj2" : {
                "_id" : "MY_OBJ_ID4",
                "prop3": "asdf",
                "prop4: "asdfasdf"
            }
        }
    ],
    "otherProp1" : "123",
    "otherProp2" : "456",
}
```

I am running the following query on a regular mongo DB:

`db.getCollection('myCollection').find({"_id": "MY_ID", "arrayData.obj2._id": "MY_OBJ_ID4"}, {"arrayData.$"})`

The document that gets returned only has the arrayData property, and the array only has one element, which is the element that matched the `obj2._id`. Thus in my code, I just get the first element in this list, and then go to the property I am interested in.

However, when running this code against Fongo, the list ends up with 4 elements, and these elements have all null fields. This results in a NullPointerException. Below are logs from this:

```
10:39:14.496 [main] DEBUG com.mongodb.FongoDBCollection - applying projections { "arrayData.$" : 1}
10:39:14.496 [main] DEBUG com.mongodb.FongoDBCollection - found results [{ "_id" : "MY_ID" , "arrayData" : [ { } , { } , { } , { }]}]
```

Is this expected behavior? Is it on the roadmap to support this?

**Comment by twillouer** [comment]
```java
    final DBCollection collection = newCollection();
    fongoRule.parseDBObject("{\n" +
        "    \"_id\" : \"MY_ID\",\n" +
        "    \"arrayData\" : [ \n" +
        "        {\n" +
        "            \"obj1\" : {\n" +
        "                \"prop1\" : \"foo\",\n" +
        "                \"prop2\" : \"bar\"\n" +
        "            },\n" +
        "            \"obj2\" : {\n" +
        "                \"_id\" : \"MY_OBJ_ID1\",\n" +
        "                \"prop3\": \"asdf\",\n" +
        "                \"prop4\": \"asdfasdf\"\n" +
        "            }\n" +
        "        }, \n" +
        "        {\n" +
        "            \"obj1\" : {\n" +
        "                \"prop1\" : \"foo\",\n" +
        "                \"prop2\" : \"bar\"\n" +
        "            },\n" +
        "            \"obj2\" : {\n" +
        "                \"_id\" : \"MY_OBJ_ID2\",\n" +
        "                \"prop3\": \"asdf\",\n" +
        "                \"prop4\": \"asdfasdf\"\n" +
        "            }\n" +
        "        }, \n" +
        "        {\n" +
        "            \"obj1\" : {\n" +
        "                \"prop1\" : \"foo\",\n" +
        "                \"prop2\" : \"bar\"\n" +
        "            },\n" +
        "            \"obj2\" : {\n" +
        "                \"_id\" : \"MY_OBJ_ID3\",\n" +
        "                \"prop3\": \"asdf\",\n" +
        "                \"prop4\": \"asdfasdf\"\n" +
        "            }\n" +
        "        }, \n" +
        "        {\n" +
        "            \"obj1\" : {\n" +
        "                \"prop1\" : \"foo\",\n" +
        "                \"prop2\" : \"bar\"\n" +
        "            },\n" +
        "            \"obj2\" : {\n" +
        "                \"_id\" : \"MY_OBJ_ID4\",\n" +
        "                \"prop3\": \"asdf\",\n" +
        "                \"prop4\": \"asdfasdf\"\n" +
        "            }\n" +
        "        }\n" +
        "    ],\n" +
        "    \"otherProp1\" : \"123\",\n" +
        "    \"otherProp2\" : \"456\"\n" +
        "}");

    // When
    final List<DBObject> dbObjects = collection.find(fongoRule.parseDBObject("{\"_id\": \"MY_ID\", \"arrayData.obj2._id\": \"MY_OBJ_ID4\"}"), new BasicDBObject("arrayData.$", "1")).toArray();

    // Then
    assertThat(dbObjects).isEmpty();
```

both (mongodb and fongo) return an empty result.

where am i wrong ?

**Comment by dnchristiansen** [comment]
Just to give full disclosure, I am using Spring Data MongoDB to make the calls, so it's possible there could be an issue in there. I haven't done much directly with DBObjects and other classes within com.mongodb.

I made some modifications to the code you posted, and it ended up looking like this:
```
final DBCollection collection = fongoRule.getDB().createCollection("foo", fongoRule.parseDBObject("{}"));
collection.insert(
		fongoRule.parseDBObject("{\n" +
	        "    \"_id\" : \"MY_ID\",\n" +
	        "    \"arrayData\" : [ \n" +
	        "        {\n" +
	        "            \"obj1\" : {\n" +
	        "                \"prop1\" : \"foo\",\n" +
	        "                \"prop2\" : \"bar\"\n" +
	        "            },\n" +
	        "            \"obj2\" : {\n" +
	        "                \"_id\" : \"MY_OBJ_ID1\",\n" +
	        "                \"prop3\": \"asdf\",\n" +
	        "                \"prop4\": \"asdfasdf\"\n" +
	        "            }\n" +
	        "        }, \n" +
	        "        {\n" +
	        "            \"obj1\" : {\n" +
	        "                \"prop1\" : \"foo\",\n" +
	        "                \"prop2\" : \"bar\"\n" +
	        "            },\n" +
	        "            \"obj2\" : {\n" +
	        "                \"_id\" : \"MY_OBJ_ID2\",\n" +
	        "                \"prop3\": \"asdf\",\n" +
	        "                \"prop4\": \"asdfasdf\"\n" +
	        "            }\n" +
	        "        }, \n" +
	        "        {\n" +
	        "            \"obj1\" : {\n" +
	        "                \"prop1\" : \"foo\",\n" +
	        "                \"prop2\" : \"bar\"\n" +
	        "            },\n" +
	        "            \"obj2\" : {\n" +
	        "                \"_id\" : \"MY_OBJ_ID3\",\n" +
	        "                \"prop3\": \"asdf\",\n" +
	        "                \"prop4\": \"asdfasdf\"\n" +
	        "            }\n" +
	        "        }, \n" +
	        "        {\n" +
	        "            \"obj1\" : {\n" +
	        "                \"prop1\" : \"foo\",\n" +
	        "                \"prop2\" : \"bar\"\n" +
	        "            },\n" +
	        "            \"obj2\" : {\n" +
	        "                \"_id\" : \"MY_OBJ_ID4\",\n" +
	        "                \"prop3\": \"asdf\",\n" +
	        "                \"prop4\": \"asdfasdf\"\n" +
	        "            }\n" +
	        "        }\n" +
	        "    ],\n" +
	        "    \"otherProp1\" : \"123\",\n" +
	        "    \"otherProp2\" : \"456\"\n" +
	        "}")
		);

	    // When
	    final List<DBObject> dbObjects = collection.find(fongoRule.parseDBObject("{\"_id\": \"MY_ID\", \"arrayData.obj2._id\": \"MY_OBJ_ID4\"}"), new BasicDBObject("arrayData.$", "1")).toArray();
```

Now when it runs the `find` it throws an IllegalArgumentException with the stack trace:
```
java.lang.IllegalArgumentException: Projection `arrayData.$' has a value that Fongo doesn't know how to handle: 1 (class java.lang.String)
	at com.mongodb.FongoDBCollection.applyProjections(FongoDBCollection.java:829)
	at com.mongodb.FongoDBCollection.applyProjections(FongoDBCollection.java:686)
	at com.mongodb.FongoDBCollection.__find(FongoDBCollection.java:650)
	at com.mongodb.FongoDBCursor.fetch(FongoDBCursor.java:60)
	at com.mongodb.FongoDBCursor.toArray(FongoDBCursor.java:81)
	at com.mongodb.DBCursor.toArray(DBCursor.java:645)
	...
```

Please let me know if I'm doing something wrong with the code, and I can look at it more. Thanks.

**Comment by karlitos** [comment]
This seems to be still a problem in the fongo version 2.1.0

My data looks like:
``````
{
  _id: 596dbb7e4d4b9c9c8b36a5e0,
  id: config,
  versions: [
    {
      version: 1,
      changedOn: 2017-07-18T07:40Z,
      data: {foo: bar}
    }
  ]
}
``````
So I build my queries like:
``````java
BasicDBObject match = new BasicDBObject("versions.version", 1).append("id", "config");
BasicDBObject project = new BasicDBObject("versions.$.version", 1).append("_id", 0);
Document result = collection.find(match).projection(project).first();
``````
which with fongo returns:
``````
{ "versions" : [{ }] }
``````

But, if I do
``````java
...
BasicDBObject project = new BasicDBObject("_id", 0);
...
``````
I get following result:
``````
{ "id" : "config", "versions" : [{ "version" : "1", "changedOn" : "2017-07-18T08:32Z", "data" : { "foo" : "bar" } }] }
``````
no problem with MongoDB 3.4 with the latest Java driver
