### ISSUE TITLE
$slice NullPointerException in findOneAndUpdate

### ISSUE THREAD

**Issue by toonsevrin** [fakemongo/fongo#234]
### v2.0.7

- **Fongo Behaviour**: $slice on an empty array (/non existent array) in a findOneAndUpdate operation returns a NullPointException
- **Mongo behavior**: Returns null
- **Exception thrown**:
```java
java.lang.NullPointerException
	at com.mongodb.FongoDBCollection.slice(FongoDBCollection.java:970)
	at com.mongodb.FongoDBCollection.applyProjections(FongoDBCollection.java:922)
	at com.mongodb.FongoDBCollection.findAndModify(FongoDBCollection.java:1078)
	at com.github.fakemongo.FongoConnection.command(FongoConnection.java:405)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:216)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:153)
	at com.mongodb.operation.FindAndUpdateOperation$1.call(FindAndUpdateOperation.java:306)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:232)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:223)
	at com.mongodb.operation.FindAndUpdateOperation.execute(FindAndUpdateOperation.java:303)
	at com.github.fakemongo.Fongo.execute(Fongo.java:190)
	at com.mongodb.MongoCollectionImpl.findOneAndUpdate(MongoCollectionImpl.java:407)
	at com.mongodb.FongoMongoCollection.findOneAndUpdate(FongoMongoCollection.java:17)
```
- **Replication**:
```java
MongoCollection collection = new Fongo("testfongo").getDatabase("db").getCollection("coll");
collection.findOneAndUpdate(getIdQuery(), Updates.set("randomkey", "randomvalue"), new FindOneAndUpdateOptions().upsert(true).projection(slice("key", 1)));
```

**Comment by twillouer** [comment]
Hi,

is it better in the master branch ?
