### ISSUE TITLE
NPE when using with Camel & Spring

### ISSUE THREAD

**Issue by nickbusy** [fakemongo/fongo#262]
Getting NPE while trying to test Camel context with MongoDB endpoints and Fongo.
```
Caused by: java.lang.NullPointerException
	at com.mongodb.Mongo.getAllAddress(Mongo.java:393)
	at com.mongodb.MockMongoClient.getAllAddress(MockMongoClient.java:109)
	at org.apache.camel.component.mongodb.MongoDbEndpoint.initializeConnection(MongoDbEndpoint.java:220)
	at org.apache.camel.component.mongodb.MongoDbEndpoint.createProducer(MongoDbEndpoint.java:125)
	at org.apache.camel.impl.ProducerCache.doGetProducer(ProducerCache.java:574)
	... 91 more
```

This issue has been introduced relatively recently. Fixed by changing class MockMongoClient.java:
```
  @Override
  public List<ServerAddress> getAllAddress() {
	return this.getServerAddressList();
	// return super.getAllAddress();
  }

```

**Comment by twillouer** [comment]
hi,

witch version of mongo drivers do you use ?
