### ISSUE TITLE
Should MongoCollection.dropIndex work?

### ISSUE THREAD

**Issue by jmmut** [fakemongo/fongo#279]
I'm using the mongo-java-driver 3.x API (3.4), using the classes MongoDatabase, MongoCollection and Document instead of the old DB, DBCollection and DBObject, but the MongoCollection.dropIndex() method seems not implemented. 

I see that there is a com.github.fakemongo.FongoIndexTest, but it uses the 2.x API, so, is the dropIndex (for 3.x) not done by design, not done yet, or it should work?

```
11:12:48.281 [main] DEBUG com.github.fakemongo.FongoConnection - command() database:variantWithoutAnnotation, command:{ "dropIndexes" : "variantsCollection", "index" : "annot.ct.so" }
11:12:48.281 [main] WARN com.github.fakemongo.FongoConnection - Command not implemented: { "dropIndexes" : "variantsCollection", "index" : "annot.ct.so" }
11:12:48.281 [main] DEBUG com.github.fakemongo.FongoConnection - release()

com.github.fakemongo.FongoException: Not implemented for command : { "dropIndexes" : "variantsCollection" , "index" : "annot.ct.so"}

	at com.github.fakemongo.FongoConnection.command(FongoConnection.java:552)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:216)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:207)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:146)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:139)
	at com.mongodb.operation.DropIndexOperation$1.call(DropIndexOperation.java:124)
	at com.mongodb.operation.DropIndexOperation$1.call(DropIndexOperation.java:120)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:422)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:413)
	at com.mongodb.operation.DropIndexOperation.execute(DropIndexOperation.java:120)
	at com.mongodb.operation.DropIndexOperation.execute(DropIndexOperation.java:51)
	at com.github.fakemongo.Fongo.execute(Fongo.java:208)
	at com.mongodb.MongoCollectionImpl.dropIndex(MongoCollectionImpl.java:507)
	at com.mongodb.FongoMongoCollection.dropIndex(FongoMongoCollection.java:17)
	at uk.ac.ebi.eva.dbmigration.mongodb.ExtractAnnotationFromVariantTest.testDropIndexes
```

the code that triggered that is:
```
    @Test
    public void testDropIndexes() throws Exception {
        MongoDatabase mongoDatabase = new Fongo("testServer").getDatabase("variantWithoutAnnotation");
        MongoCollection<Document> variantsCollection = mongoDatabase.getCollection("variantsCollection");
        variantsCollection.createIndex(new Document("annot.ct.so", 1), new IndexOptions().background(true));
        variantsCollection.dropIndex("annot.ct.so");
    }
```

**Comment by bobo** [comment]
Any thoughts on this?

**Comment by kalexmills** [comment]
A workaround at least would be nice. I have an integration test that could make use of it.
