### ISSUE TITLE
Fongo fails to get collection

### ISSUE THREAD

**Issue by dtracers** [fakemongo/fongo#307]
2017-09-17 17:42:13 DEBUG [FongoConnection.java:641] release() 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:598] find({ "$query" : { "ns" : "56ab003f-aaa6-441f-9211-ed61bf3cdf5a.system.users"}}, null).skip(0).limit(0) 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:599] the db 56ab003f-aaa6-441f-9211-ed61bf3cdf5a looks like 0 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:1327] searchIndex() found index null for fields [ns] 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:1049] sorted objectsToSearch [] 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:1049] sorted objectsToSearch [] 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:659] found results [] 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:472] remove: { "name" : "56ab003f-aaa6-441f-9211-ed61bf3cdf5a.system.users"} 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:1327] searchIndex() found index null for fields [name] 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:598] find({ "$query" : { "ns" : "56ab003f-aaa6-441f-9211-ed61bf3cdf5a.system.namespaces"}}, null).skip(0).limit(0) 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:599] the db 56ab003f-aaa6-441f-9211-ed61bf3cdf5a looks like 0 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:1327] searchIndex() found index null for fields [ns] 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:1049] sorted objectsToSearch [] 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:1049] sorted objectsToSearch [] 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:659] found results [] 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:472] remove: { "name" : "56ab003f-aaa6-441f-9211-ed61bf3cdf5a.system.namespaces"} 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:1327] searchIndex() found index null for fields [name] 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:598] find({ "$query" : { "ns" : "56ab003f-aaa6-441f-9211-ed61bf3cdf5a.system.indexes"}}, null).skip(0).limit(0) 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:599] the db 56ab003f-aaa6-441f-9211-ed61bf3cdf5a looks like 0 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:1327] searchIndex() found index null for fields [ns] 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:1049] sorted objectsToSearch [] 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:1049] sorted objectsToSearch [] 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:659] found results [] 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:472] remove: { "name" : "56ab003f-aaa6-441f-9211-ed61bf3cdf5a.system.indexes"} 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:1327] searchIndex() found index null for fields [name] 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:598] find({ "$query" : { "ns" : "56ab003f-aaa6-441f-9211-ed61bf3cdf5a.system.namespaces"}}, null).skip(0).limit(0) 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:599] the db 56ab003f-aaa6-441f-9211-ed61bf3cdf5a looks like 0 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:1327] searchIndex() found index null for fields [ns] 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:1049] sorted objectsToSearch [] 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:1049] sorted objectsToSearch [] 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:659] found results [] 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:472] remove: { "name" : "56ab003f-aaa6-441f-9211-ed61bf3cdf5a.system.namespaces"} 
2017-09-17 17:42:13 DEBUG [FongoDBCollection.java:1327] searchIndex() found index null for fields [name] 

java.lang.AbstractMethodError: com.github.fakemongo.FongoConnection.command(Ljava/lang/String;Lorg/bson/BsonDocument;Lcom/mongodb/ReadPreference;Lorg/bson/FieldNameValidator;Lorg/bson/codecs/Decoder;)Ljava/lang/Object;

	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:214)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:205)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:111)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:715)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:709)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:429)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:402)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:709)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:81)
	at com.github.fakemongo.Fongo.execute(Fongo.java:179)
	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:871)
	at com.mongodb.DBCursor.hasNext(DBCursor.java:142)
	at com.mongodb.DBCursor.one(DBCursor.java:680)
	at com.mongodb.DBCollection.findOne(DBCollection.java:832)
	at com.mongodb.DBCollection.findOne(DBCollection.java:795)
	at com.mongodb.DBCollection.findOne(DBCollection.java:742)
	at com.mongodb.FongoDBCollection.createIndex(FongoDBCollection.java:515)
	at com.mongodb.FongoDBCollection.<init>(FongoDBCollection.java:92)
	at com.mongodb.FongoDB.doGetCollection(FongoDB.java:98)
	at com.mongodb.FongoDB.doGetCollection(FongoDB.java:89)
	at com.mongodb.FongoDB.getCollection(FongoDB.java:84)
	at com.mongodb.FongoMongoCollection.<init>(FongoMongoCollection.java:26)
	at com.mongodb.FongoMongoDatabase.getCollection(FongoMongoDatabase.java:47)
	at com.mongodb.MongoDatabaseImpl.getCollection(MongoDatabaseImpl.java:110)
	at com.mongodb.FongoMongoDatabase.getCollection(FongoMongoDatabase.java:11)

This happens with the name "COURSE"
I am using a FongoRule
And it is version 2.1.0

not sure what happened but all of a sudden it is failing on getting the collection when it did not used to fail at this

**Comment by twillouer** [comment]
Hi,

can you provide me the mongodb drivers version and the call to "getCollection"

it's only
```
fongoRule.getCollection("COURSE");
```
?

**Comment by mrdrozdov** [comment]
@twillouer was this ever resolved?

**Comment by mrdrozdov** [comment]
Setting the mongo version to 3.5 resolved this for me. I wasn't using fongoRule, but just fongo.
