### ISSUE TITLE
NullPointerException at ExpressionParser

### ISSUE THREAD

**Issue by TomerCherni** [fakemongo/fongo#323]
When compere  "queryComp" object and the object is null get:
ava.lang.NullPointerException: null
	at com.github.fakemongo.impl.ExpressionParser.compareObjects(ExpressionParser.java:722)
	at com.github.fakemongo.impl.ExpressionParser.access$000(ExpressionParser.java:44)
	at com.github.fakemongo.impl.ExpressionParser$InFilterFactory.containsWithRegex(ExpressionParser.java:1346)
	at com.github.fakemongo.impl.ExpressionParser$InFilterFactory.compare(ExpressionParser.java:1335)
	at com.github.fakemongo.impl.ExpressionParser$InFilterFactory$1.apply(ExpressionParser.java:1318)
	at com.github.fakemongo.impl.ExpressionParser$AndFilter.apply(ExpressionParser.java:1127)
	at com.github.fakemongo.impl.ExpressionParser$AndFilter.apply(ExpressionParser.java:1127)
	at com.github.fakemongo.impl.ExpressionParser$9.compare(ExpressionParser.java:254)
	at com.github.fakemongo.impl.ExpressionParser$BasicFilterFactory$1.apply(ExpressionParser.java:1246)
	at com.github.fakemongo.impl.ExpressionParser$AndFilter.apply(ExpressionParser.java:1127)
	at com.github.fakemongo.impl.ExpressionParser$AndFilter.apply(ExpressionParser.java:1127)
	at com.github.fakemongo.impl.ExpressionParser$OrFilter.apply(ExpressionParser.java:1139)
	at com.github.fakemongo.impl.ExpressionParser$NotFilter.apply(ExpressionParser.java:1108)
	at com.github.fakemongo.impl.ExpressionParser$AndFilter.apply(ExpressionParser.java:1127)
	at com.github.fakemongo.impl.ExpressionParser$AndFilter.apply(ExpressionParser.java:1127)
	at com.github.fakemongo.impl.ExpressionParser$AndFilter.apply(ExpressionParser.java:1127)
	at com.github.fakemongo.impl.ExpressionParser$AndFilter.apply(ExpressionParser.java:1127)
	at com.github.fakemongo.impl.ExpressionParser$AndFilter.apply(ExpressionParser.java:1127)

**Comment by TomerCherni** [comment]
@twillouer please review: https://github.com/TomerCherni/fongo/pull/1
