### ISSUE TITLE
When using $elemMatch on an array field, Fongo tries to cast every item to DBObject, and throws an exception

### ISSUE THREAD

**Issue by shaikap** [fakemongo/fongo#90]
```
java.lang.ClassCastException: java.lang.String cannot be cast to com.mongodb.DBObject
	at com.github.fakemongo.impl.ExpressionParser$8.compare(ExpressionParser.java:552) ~[fongo-1.5.9.jar:na]
	at com.github.fakemongo.impl.ExpressionParser$BasicFilterFactory$1.apply(ExpressionParser.java:252) ~[fongo-1.5.9.jar:na]
	at com.github.fakemongo.impl.ExpressionParser$AndFilter.apply(ExpressionParser.java:1125) ~[fongo-1.5.9.jar:na]
	at com.github.fakemongo.impl.ExpressionParser$NotFilter.apply(ExpressionParser.java:1106) ~[fongo-1.5.9.jar:na]
	at com.github.fakemongo.impl.ExpressionParser$AndFilter.apply(ExpressionParser.java:1125) ~[fongo-1.5.9.jar:na]
	at com.mongodb.FongoDBCollection.update(FongoDBCollection.java:233) ~[fongo-1.5.9.jar:na]
	at com.mongodb.DBCollection.update(DBCollection.java:191) ~[mongo-java-driver-2.12.4.jar:na]
	at com.mongodb.DBCollection.update(DBCollection.java:224) ~[mongo-java-driver-2.12.4.jar:na]
	at com.mongodb.DBCollection.updateMulti(DBCollection.java:254) ~[mongo-java-driver-2.12.4.jar:na]
```

**Comment by twillouer** [comment]
Hi,

thanks for the report.
Can you provide a test case and can you try the latest version (1.5.10) before ?

**Comment by twillouer** [comment]
@shaikap reproduced in 1.5.10
