### ISSUE TITLE
fongo not compatible with mongo driver 2.13.0?

### ISSUE THREAD

**Issue by eskamuc** [fakemongo/fongo#97]
Hi,
thank you for fongo, which makes testing much faster for us.
But maybe, there's an issue with fongo and mongo driver 2.13.0.
After upgrading the driver to this version we got the following error, which disappeared, when downgrading to 2.12.5:

java.lang.AbstractMethodError: com.mongodb.DBCollection.getIndexInfo()Ljava/util/List;
	at xxxxxxxxxxxxxxxxxxxxxxxxxxxx.mongo.MongoDAO.ensureIndex(MongoDAO.java:346)
	at xxxxxxxxxxxxxxxxxxxxxxxxxxxx.mongo.MongoDAO.ensureIndexes(MongoDAO.java:135)
	at xxxxxxxxxxxxxxxxxxxxxxxxxxxx.mongo.MongoDAO.<init>(MongoDAO.java:102)
	at xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxMongoDAOImpl.<init>(WorkspaceMongoDAOImpl.java:56)
	at xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.MongoDAOFactory.initDAOs(MongoDAOFactory.java:99)
	at xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.MongoDAOFactory.<init>(MongoDAOFactory.java:95)
	at xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.FakeMongoRule.before(FakeMongoRule.java:31)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)

The packages "xx.*" are our own, but we think, the reason lies in fongo, because fongo creates a mock object of the MongoClient class.

Regards,
  Stefan

**Comment by eskamuc** [comment]
Maybe, it's related to https://github.com/fakemongo/fongo/issues/95
Sorry, if I reported a duplicate.
